#!/usr/bin/env ruby

require 'shellwords'

unless ARGV[0]
  puts <<-EOF
Usage: ./script/#{__FILE__} COMMAND [ARGS]

The command will be run in the context of the local Rails
app stored in test-rails-app.

Examples:

./script/local server
./script/local c
./script/local rake db:migrate
  EOF
  exit(1)
end

require 'rails'

# Set up some variables
dir = ".test-rails-apps"
path = "#{dir}/test-rails-app-#{Rails.version}"
gemfile_name = "rails_#{Rails::VERSION::MAJOR}.gemfile"
gemfile = File.expand_path("../gemfiles/#{gemfile_name}", File.dirname(__FILE__))

# Ensure .test-rails-apps is created
system "mkdir #{dir}" unless File.exists?(dir)

# Create the sample Rails app if it doesn't already exist
unless File.exists? path
  args = %w[
    -m\ spec/support/rails_template_with_data.rb
    --skip-gemfile
    --skip-bundle
    --skip-git
    --skip-turbolinks
    --skip-test-unit
  ]
  system "BUNDLE_GEMFILE=#{gemfile} bundle exec rails new #{Shellwords.escape path} #{args.join ' '}"
end

# Link this Rails app
system "rm test-rails-app"
system "ln -s #{Shellwords.escape path} test-rails-app"

# If it's a Rails command, auto add the `rails` script
RAILS_COMMANDS = %w{generate console server dbconsole g c s runner}
args = RAILS_COMMANDS.include?(ARGV[0]) ? ["rails", ARGV].flatten : ARGV

# Run the command
exec "cd test-rails-app && BUNDLE_GEMFILE=#{gemfile} bundle exec #{args.join(" ")}"
